
server:
  port: 10000
  servlet:
    context-path: /
#  address: localhost

#spring:
#  profiles:
#    active: company_rw


mybatis:
  configuration:
    map-underscore-to-camel-case: true


spring:
  shardingsphere:
    datasource:
      names: ds1
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.5.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 123456
#  config:
    sharding:
      tables:
        t_order:
#          actual-data-nodes: ds->{1}.t_order
          actual-data-nodes: ds1.t_order
          table-strategy:
            standard:
              sharding-column: sale_date
              precise-algorithm-class-name: com.kq.sharding.algorithm.OrderTimePreciseShardingAlgorithm

      default-data-source-name: ds1

    props:
      sql:
        show: true






