server:
  port: 10001
#  servlet:
#    context-path: /
#  address: localhost


mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  main:
    allow-bean-definition-overriding: true  # 这个要配置bootstrap文件  配置在application.yml起步动
  datasource:
#    url: jdbc:mysql://mysql.kq.com:23306/attendancedb?autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    url: jdbc:mysql://172.16.5.149:6006/attendancedb?autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    initialization-mode: always
    tomcat:
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)