
server:
  port: 10001
  servlet:
    context-path: /sharding-jdbc-4
#  address: localhost

#spring:
#  profiles:
#    active: company_rw


mybatis:
  configuration:
    map-underscore-to-camel-case: true








